# Generated by Django 3.2 on 2021-04-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_auto_20210424_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='slug',
        ),
    ]
